spring.application.name=cantrace-backend
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cantrace}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cantrace}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cantrace}
spring.datasource.driver-class-name=org.postgresql.Driver
